# Generated by Django 2.2.7 on 2020-01-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200106_0140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
