# Generated by Django 2.2.7 on 2019-12-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_auto_20191225_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body_text',
            field=models.TextField(default='another body text created now'),
        ),
    ]
