# Generated by Django 2.2.7 on 2020-01-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20191225_1758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
