# Generated by Django 3.0.4 on 2020-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('profile_pic', models.ImageField(blank=True, upload_to='uploads/img/profilepics/')),
            ],
        ),
        migrations.AlterField(
            model_name='wuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/img/profilepics/'),
        ),
    ]
