# Generated by Django 3.0.4 on 2020-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200327_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePics',
        ),
    ]
