# Generated by Django 3.0.4 on 2020-03-27 16:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_profilepics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=accounts.models.filename_generator),
        ),
    ]
