# Generated by Django 2.2.7 on 2019-12-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191224_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='simple',
        ),
    ]
