# Generated by Django 3.0.4 on 2020-03-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200327_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuser',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
    ]
