# Generated by Django 2.2.5 on 2019-11-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cardDate',
            new_name='card_date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Question',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='cardlike',
            old_name='likeDate',
            new_name='like_date',
        ),
        migrations.RenameField(
            model_name='cardlike',
            old_name='likeTime',
            new_name='like_time',
        ),
        migrations.RenameField(
            model_name='cardreply',
            old_name='replyDate',
            new_name='reply_date',
        ),
        migrations.RenameField(
            model_name='cardreply',
            old_name='replyTime',
            new_name='reply_time',
        ),
    ]
