# Generated by Django 2.2.5 on 2019-11-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20191118_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
