# Generated by Django 2.2.5 on 2019-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_card_card_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_time',
            field=models.TimeField(),
        ),
    ]
