# Generated by Django 2.2.7 on 2019-12-29 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk', '0004_auto_20191120_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0, help_text='determines whether a vote is up or down: 1 is upvote & 2 is downvote')),
                ('like_date', models.DateField(auto_now_add=True)),
                ('like_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cardreply',
            name='reply_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cardreply',
            name='reply_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cardreply',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='CardLike',
        ),
        migrations.AddField(
            model_name='cardvote',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Card'),
        ),
        migrations.AddField(
            model_name='cardvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='votes',
            field=models.ManyToManyField(related_name='card_votes', through='desk.CardVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
