# Generated by Django 2.2.7 on 2019-12-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_auto_20191229_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardvote',
            old_name='like_date',
            new_name='vote_date',
        ),
        migrations.RenameField(
            model_name='cardvote',
            old_name='like_time',
            new_name='vote_time',
        ),
    ]
