# Generated by Django 2.2.7 on 2020-01-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_auto_20191231_0137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='cards',
        ),
        migrations.AlterModelTable(
            name='cardreply',
            table='cardreplies',
        ),
        migrations.AlterModelTable(
            name='cardvote',
            table='cardvotes',
        ),
    ]
