# Generated by Django 2.2.7 on 2020-01-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0007_auto_20200106_0145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cardreply',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cardvote',
            table=None,
        ),
    ]
