# Generated by Django 2.2.7 on 2020-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_time', models.TimeField(auto_now_add=True)),
                ('error_type', models.CharField(max_length=300)),
                ('error_msg', models.TextField()),
                ('app', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
