# Generated by Django 2.2.7 on 2019-12-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logDate', models.DateField(auto_now_add=True)),
                ('logTime', models.TimeField(auto_now_add=True)),
                ('errorType', models.CharField(max_length=300)),
                ('errorMsg', models.TextField()),
                ('app', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
