# Generated by Django 2.2.7 on 2019-12-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlogger',
            old_name='errorMsg',
            new_name='error_msg',
        ),
        migrations.RenameField(
            model_name='errorlogger',
            old_name='errorType',
            new_name='error_type',
        ),
        migrations.RenameField(
            model_name='errorlogger',
            old_name='logDate',
            new_name='log_date',
        ),
        migrations.RenameField(
            model_name='errorlogger',
            old_name='logTime',
            new_name='log_time',
        ),
    ]
