# Generated by Django 2.2.7 on 2019-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20191227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogger',
            name='user_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
